title : JaiBhavani Muppidi 
description : This portfolio showcases my data analysis skills and projects 
contact info : 
    Email -  jaibhavani1706@gmail.com
    phone -  9701335324
    GitHub - https://mjaibhavani.github.io/JAIBHAVANI_portfolio
theme : jekyll-theme-minimal

